### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by JSON-HATES-BOTS** [paragbaxi/safeshifter#1]
jasons-mbp:safeshifter jason.kentcequence.ai$ node node_modules/@safeshifter/safeshifter/dist/instagram.js
(node:30436) UnhandledPromiseRejectionWarning: TypeError: text is not iterable
    at Keyboard.type (/Users/jason.kentcequence.ai/safeshifter/node_modules/puppeteer/lib/Input.js:160:24)
    at Keyboard.<anonymous> (/Users/jason.kentcequence.ai/safeshifter/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.type (/Users/jason.kentcequence.ai/safeshifter/node_modules/puppeteer/lib/JSHandle.js:336:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DOMWorld.type (/Users/jason.kentcequence.ai/safeshifter/node_modules/puppeteer/lib/DOMWorld.js:422:5)
    at async /Users/jason.kentcequence.ai/safeshifter/node_modules/@safeshifter/safeshifter/dist/instagram.js:47:3
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/jason.kentcequence.ai/safeshifter/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.type (/Users/jason.kentcequence.ai/safeshifter/node_modules/puppeteer/lib/DOMWorld.js:422:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/jason.kentcequence.ai/safeshifter/node_modules/@safeshifter/safeshifter/dist/instagram.js:47:3
  -- ASYNC --
    at Frame.<anonymous> (/Users/jason.kentcequence.ai/safeshifter/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.type (/Users/jason.kentcequence.ai/safeshifter/node_modules/puppeteer/lib/Page.js:1106:29)
    at /Users/jason.kentcequence.ai/safeshifter/node_modules/@safeshifter/safeshifter/dist/instagram.js:47:14
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:30436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by paragbaxi** [comment]
set $INSTAGRAM_USER and $INSTAGRAM_PWD
